### ISSUE TITLE
 No such file or directory - stty size

### ISSUE THREAD

**Issue by eric-smartlove** [busyloop/powerbar#5]
Hello, I am a powerbar user now that minitest-reporters use it since v0.9.0 (see https://github.com/CapnKernul/minitest-reporters/pull/23)

However, I may have a problem with powerbar, when I use the `ProgressReporter` in minitest-reporters, that seems to use powerbar. I obtain the following message when I run a test:
```
./test/unit/models/user/attributes_test.rb: No such file or directory - stty size
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/powerbar-1.0.7/lib/powerbar.rb:337:in `rescue in block (2 levels) in render_template': Invalid token 'bar' in template 'main' (NameError)
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/powerbar-1.0.7/lib/powerbar.rb:334:in `block (2 levels) in render_template'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/powerbar-1.0.7/lib/powerbar.rb:332:in `gsub'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/powerbar-1.0.7/lib/powerbar.rb:332:in `block in render_template'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/powerbar-1.0.7/lib/powerbar.rb:330:in `gsub'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/powerbar-1.0.7/lib/powerbar.rb:330:in `render_template'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/powerbar-1.0.7/lib/powerbar.rb:226:in `render'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/powerbar-1.0.7/lib/powerbar.rb:218:in `show'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/minitest-reporters-0.9.0/lib/minitest/reporters/progress_reporter.rb:46:in `increment'
  ...
```
Although I use powerbar in the context of minitest-reporter, that seems to be a powerbar issue.

It may be related to Windows, as I've discovered there was a similar problem for another gem here: http://www.ruby-forum.com/topic/168877#741778.

Other related thread: http://stackoverflow.com/questions/3677735/equivalent-to-stty-size-on-windows

I use Windows XP and  ruby 1.9.3-p125

**Comment by m-o-e** [comment]
According to https://github.com/rubyworks/ansi/issues/12#issuecomment-69062516 this should be fixed now.

Can someone test if the current powerbar version (1.0.12) now works on windows?

**Comment by m-o-e** [comment]
Closing this issue due to inactivity, assuming the bug is fixed.
